services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    container_name: postgres_r2dbc
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"

  kms:
    image: kurento/kurento-media-server:latest
    platform: linux/amd64
    container_name: kms
    ports:
      - "8888:8888"
    restart: always
    environment:
      - KMS_MIN_PORT=40000
      - KMS_MAX_PORT=40050
      - KURENTO_LOG_LEVEL=DEBUG
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUM_PORT=19302
      - KMS_TURN_URL=aim14:aim14@13.124.102.218:3478?transport=udp
#    volumes:
#      - ./WebRtcEndpoint.conf.ini:/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: aim_14
      RABBITMQ_DEFAULT_PASS: aim14pass
    ports:
      - "5672:5672"
      - "15672:15672" # 관리 웹 UI 포트

  coturn:
    image: coturn/coturn
    container_name: coturn_server
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf
    restart: always