spring:
  application:
    name: pitching-server

redis:
  host: localhost
  port: 6379
  maxlen: 500

server:
  port: 8080
  call:
    protocol: ws
    host: localhost
    voice-path: /ws/v1/voice
    video-path: /ws/v1/video
    heartbeat-interval: 45s
