spring:
  application:
    name: pitching-server

server:
  port: 8080
  call:
    protocol: ws
    host: localhost
    voice-path: /ws/v1/voice
    video-path: /ws/v1/video
    heartbeat-interval: 45s

