spring:
  application:
    name: pitching-server

server:
  port: 8080
  voice:
    protocol: ws
    host: localhost
    path: /ws/v1/voice
    resume-path: /ws/v1/resume/voice
    heartbeat-interval: 45s

