spring:
  application:
    name: pitching-test
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-google-client-id
            client-secret: test-google-client-secret
            scope:
              - email
              - profile
          naver:
            client-id: test-naver-client-id
            client-secret: test-naver-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          kakao:
            client-id: test-kakao-client-id
            client-secret: test-kakao-client-secret
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=PostgreSQL
    username: sa
    password:

jwt:
  secret: test-jwt-secret-key
  access-token:
    expiration: PT1H
  refresh-token:
    expiration: P7D

front:
  url: http://localhost:5173

redis:
  host: localhost
  port: 6379
  maxlen: 500

server:
  port: 8080
  call:
    protocol: ws
    host: localhost
    websocket-path: /ws/v1/voice
    heartbeat-interval: 450s