spring:
  application:
    name: pitching-server

server:
  port: 8080
  voice:
    protocol: ws
    host: localhost
    path: /ws/voice
    resume-path: /ws/resume/voice
    version: 1
    heartbeat-interval: 45s

