spring:
  application:
    name: pitching-server

redis:
  host: localhost
  port: 6379
  maxlen: 500

server:
  port: 8080
  call:
    protocol: ws
    host: localhost
    websocket-path: /ws/v1/voice
    heartbeat-interval: 45s

logging:
  level:
    reactor.netty.udp: DEBUG

